# Nome da Aplicação e Porta
spring.application.name=gestao-licita-nc
server.port=8080

# Conexão com o Banco de Dados PostgreSQL Local
spring.datasource.url=jdbc:postgresql://localhost:5432/gestaolicitanc_db
spring.datasource.username=postgres
spring.datasource.password=1234

# Configurações do Hibernate (Mágica que cria as tabelas automaticamente para nós)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

cloud.oracle.s3.access-key=530d08a55820342c9cc40b4f04da8867cdb23156
cloud.oracle.s3.secret-key=xHMh4Y5rmrh2XkVcfaMru8VDGQayD78kpvt1G5IWyus=
cloud.oracle.s3.region=sa-saopaulo-1
cloud.oracle.s3.bucket=licitagestor-editais
cloud.oracle.s3.endpoint=https://grscxgdqcwhp.compat.objectstorage.sa-saopaulo-1.oraclecloud.com

# Configuração para permitir arquivos grandes (PDFs de editais costumam ser pesados)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB