# Nome da Aplicação e Porta
spring.application.name=gestao-licita-nc
server.port=8080

# Conexão com o Banco de Dados PostgreSQL Local
spring.datasource.url=jdbc:postgresql://localhost:5432/gestaolicitanc_db
spring.datasource.username=postgres
spring.datasource.password=1234

# Configurações do Hibernate (Mágica que cria as tabelas automaticamente para nós)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configurações do Oracle Cloud Object Storage (S3 Compatible API)
cloud.storage.endpoint=https://{SEU_NAMESPACE}.compat.objectstorage.{REGIAO}.oraclecloud.com
cloud.storage.bucket-name=licitagestor-editais
cloud.storage.access-key=sua_access_key_aqui
cloud.storage.secret-key=sua_secret_key_aqui

# Configuração para permitir arquivos grandes (PDFs de editais costumam ser pesados)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB