# CONFIGURAÇÃO DO BANCO DE DADOS POSTGRESQL (NEON NUVEM)
spring.datasource.url=jdbc:postgresql://ep-solitary-wave-axczn3we-pooler.c-4.us-east-2.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_2tIcpQM7lwHd

# COMANDOS PARA O JAVA CRIAR AS TABELAS AUTOMATICAMENTE NA NUVEM
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# CONFIGURAÇÃO DE UPLOAD E PORTA
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
server.port=8080